### ISSUE TITLE
which ray version 

### ISSUE THREAD

**Issue by zdx3578** [NeuromorphicComputing/STPN#1]
in  │ray                                2.4.0
got error: 
/STPN/AtariMujoco/run-pong.py", line 128, in <module>
    stpn_experiments = Experiment("stpn_configs", **stpn_configs)
TypeError: __init__() got an unexpected keyword argument 'keep_checkpoints_num'

**Comment by zdx3578** [comment]
what os?
what os version?

**Comment by zdx3578** [comment]
pip install ray==2.4.0  need change config
 "rollout_fragment_length": 'auto',  and delete error config

pip install tensorflow_probability

**Comment by hector-gr** [comment]
Hello,

The instructions for [dependencies](https://github.com/NeuromorphicComputing/STPN/tree/master/AtariMujoco#dependencies) specify installing   ray==2.0.0dev0 for Linux.
